# Generated by Django 3.2.5 on 2022-03-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_alter_jobmodel_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='work_type',
            field=models.CharField(choices=[('Обяви за работа', 'Обяви за работа'), ('Предлагам Услуга', 'Предлагам Услуга'), ('Търся Работа', 'Търся Работа')], default='Търся Хора', max_length=50),
        ),
    ]
