# Generated by Django 3.2.5 on 2022-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_jobmodel_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
